name: Terraform Pipeline - V3

on:
  workflow_dispatch:

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print Terraform Init
        run: echo "terraform init -backend-config=\"bucket=${{ vars.BUCKET_NAME }}\""

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init
    environment: dev
    steps:
      - name: Print Terraform Plan
        run: echo "terraform plan"

  Approval-to-deploy:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: approval
    steps:
      - name: Waiting for approval
        run: echo "Approved to deploy"

  terraform-apply:
    runs-on: ubuntu-latest
    needs: Approval-to-deploy
    environment: dev
    steps:
      - name: Print Terraform Apply
        run: echo "terraform apply -auto-approve"
