name: Terraform Pipeline - V1

on:
  push:
  workflow_dispatch:

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print Terraform Init
        run: echo "terraform init -backend-config=\"bucket=${BUCKET_NAME}\""

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init
    environment: dev
    steps:
      - name: Print Terraform Plan
        run: echo "terraform plan"

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: dev
    steps:
      - name: Print Terraform Apply
        run: echo "terraform apply -auto-approve"
